[workspace]
members = [
    "plerkle",
    "nft_api",
    "nft_ingester",
    "programs/bubblegum",
    "programs/gummyroll",
    "programs/gumball-machine",
    "programs/gummyroll_crud",
    "messenger"
]
exclude = [
    "deps",
    "programs/",
]
