apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - context: .
      image: public.ecr.aws/k2z7t6t6/metaplex-rpc-load-generator
      docker:
        dockerfile: Load.Dockerfile
    - context: .
      image: public.ecr.aws/k2z7t6t6/metaplex-rpc-api
      docker:
        dockerfile: Api.Dockerfile
    - context: .
      image: public.ecr.aws/k2z7t6t6/metaplex-rpc-ingest
      docker:
        dockerfile: Ingest.Dockerfile
deploy:
  helm:
    releases:
      - name: das-ingester
        chartPath: helm/ingest
        artifactOverrides:
          image: public.ecr.aws/k2z7t6t6/metaplex-rpc-ingest
          loadImage: public.ecr.aws/k2z7t6t6/metaplex-rpc-load-generator
        setValueTemplates:
          ingest.db_url: "{{.DATABASE_URL}}"
          ingest.redis_url: "{{.REDIS_URL}}"
          metrics.data_dog_api_key: "{{.DATA_DOG_API}}"
        valuesFiles:
          - ./helm/ingest/values.yaml
      - name: das-api
        chartPath: helm/api
        artifactOverrides:
          image: public.ecr.aws/k2z7t6t6/metaplex-rpc-api
        setValueTemplates:
          api.db_url: "{{.DATABASE_URL}}"
          api.redis_url: "{{.REDIS_URL}}"
          metrics.data_dog_api_key: "{{.DATA_DOG_API}}"
        valuesFiles:
          - ./helm/api/values.yaml
    flags:
      upgrade: [ "--timeout","900s" ]
      install: [ "--timeout","900s" ]
profiles:
  - name: dev
    patches:
      - op: replace
        path: /deploy/helm/releases/0/valuesFiles/0
        value: ./helm/values-testnet.yaml
      - op: replace
        path: /deploy/helm/releases/1/valuesFiles/1
        value: ./helm/values-testnet.yaml