apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  labels:
    app: load
    {{- include "ingest.labels" . | nindent 4 }}
spec:
  replicas: 5
  selector:
    matchLabels:
      app: load
      {{- include "ingest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: load
        {{- include "ingest.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: Always
      containers:
        - name: load-gen
          image: {{.Values.loadImage}}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          readinessProbe:
            exec:
              command:
                - echo
                - "true"
          livenessProbe:
            exec:
              command:
                - echo
                - "true"
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"

