apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingest.secret" . }}
data:
  INGESTER_DATABASE_URL: {{ .Values.ingest.db_url | b64enc | quote }}
  INGESTER_MESSENGER_CONFIG: {{ (printf "{redis_connection_str=%s}" .Values.ingest.redis_url) | b64enc | quote }}